# vim: set ft=yaml :
#
# https://taskfile.dev


version: '3'

set: ['errexit', 'nounset', 'pipefail']

includes:

  uv:
    taskfile: '.taskfile-library/include/uv'
    vars:
      PYTHON_MINOR_VERSION: '3.12'
